version: '3.8' # Specify docker-compose version

services:
  backend:
    build: ./backend 
    container_name: battery_backend
    ports:
      - "5001:5000"
    volumes:
      - ./models:/app/models:ro
      - ./data:/app/data:ro
    networks:
      - battery_net
    restart: unless-stopped

  frontend:
    build: ./frontend 
    container_name: battery_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data:ro
    environment:
      - API_BASE_URL=http://backend:5000
      
    networks:
      - battery_net
    depends_on:
      - backend
    restart: unless-stopped

networks:
  battery_net: 
    driver: bridge